name: vacunas-app

services:
  bd-vacunas:
    build:
      secrets:
        - MSSQL_SA_PASSWORD
      dockerfile: Dockerfile
    container_name: sql-server-vacunas
    ports:
      - "1440:1433"
    secrets:
      - MSSQL_SA_PASSWORD
    restart: on-failure
    volumes:
      - bd-data:/var/opt/mssql
    networks:
      network-vacunas:
        ipv4_address: 172.22.0.2
    healthcheck:
      test: [ "CMD-SHELL", "/usr/src/app/test-check.sh" ]
      interval: 10s
      retries: 10
      start_period: 90s
      timeout: 10s

  redis-vacunas:
    image: redis/redis-stack:latest
    container_name: cache-redis-vacunas
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - cache-persistence:/data
      - ./redis.conf:/redis-stack.conf
    networks:
      network-vacunas:
        ipv4_address: 172.22.0.3

#  rabbitmq-vacunas:
#    image: rabbitmq:management-alpine
#    container_name: msg-rabbitmq-vacunas
#    restart: always
#    ports:
#      - "15692:15692"
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - msg-broker-rabbitmq:/var/lib/rabbitmq
#      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
#      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#    networks:
#      network-vacunas:
#        ipv4_address: 172.22.0.4

  api-vacunas:
    image: api-vacunas-panama:0.8.0
    container_name: api-spring-vacunas
    env_file:
      - "secrets/docker.env"
    secrets:
      - JWT_PUBLIC_KEY
      - JWT_PRIVATE_KEY
        #restart: on-failure
    depends_on:
      bd-vacunas:
        condition: service_healthy
      redis-vacunas:
        condition: service_started
      # rabbitmq-vacunas:
        # condition: service_started
    ports:
      - "8080:8080"
    networks:
      network-vacunas:
        ipv4_address: 172.22.0.5

volumes:
  bd-data:
    driver: local
  cache-persistence:
    driver: local
  msg-broker-rabbitmq:
    driver: local

networks:
  network-vacunas:
    attachable: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

secrets:
  MSSQL_SA_PASSWORD:
    file: secrets/db.env
  JWT_PUBLIC_KEY:
    file: secrets/public.pem
  JWT_PRIVATE_KEY:
    file: secrets/private.pem
