-- tables with PK, NOT NULL, default and UNIQUE CONSTRAINTs
CREATE TABLE direcciones
(
    id         UUID         NOT NULL DEFAULT gen_random_UUID(),
    direccion  VARCHAR(150) NOT NULL, -- NOSONAR
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0),
    distrito   SMALLINT     NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE distritos
(
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1),
    provincia SMALLINT     NOT NULL,
    nombre    VARCHAR(100) NOT NULL, -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE doctores
(
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0),
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    sede       UUID,
    idoneidad  VARCHAR(20)  NOT NULL, -- NOSONAR
    categoria  VARCHAR(100),          -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE dosis
(
    numero_dosis     VARCHAR(2)   NOT NULL, -- NOSONAR
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now(),
    fecha_aplicacion TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(0),
    doctor           UUID,
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    paciente         UUID         NOT NULL,
    sede             UUID         NOT NULL,
    vacuna           UUID         NOT NULL,
    lote             VARCHAR(50),           -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE entidades
(
    disabled    BOOLEAN      NOT NULL DEFAULT FALSE,
    dependencia VARCHAR(13),                            -- NOSONAR
    telefono    VARCHAR(15),                            -- NOSONAR
    direccion   UUID         NOT NULL,
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    estado      VARCHAR(50)  NOT NULL DEFAULT 'ACTIVO', -- NOSONAR
    nombre      VARCHAR(100) NOT NULL,                  -- NOSONAR
    correo      VARCHAR(254),                           -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE fabricantes
(
    created_at        TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP(0),
    contacto_telefono VARCHAR(15),           -- NOSONAR
    id                UUID         NOT NULL DEFAULT gen_random_uuid(),
    usuario           UUID,
    licencia          VARCHAR(50)  NOT NULL, -- NOSONAR
    contacto_nombre   VARCHAR(100),          -- NOSONAR
    contacto_correo   VARCHAR(254),          -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE fabricantes_vacunas
(
    fabricante UUID NOT NULL,
    vacuna     UUID NOT NULL,
    PRIMARY KEY (fabricante, vacuna)
);

CREATE TABLE pacientes
(
    created_at              TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP(0),
    id                      UUID         NOT NULL DEFAULT gen_random_uuid(),
    identificacion_temporal VARCHAR(255), -- NOSONAR
    PRIMARY KEY (id),
    CONSTRAINT uq_pacientes_id_temporal UNIQUE (identificacion_temporal)
);

CREATE TABLE permisos
(
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(0),
    descripcion VARCHAR(100),          -- NOSONAR
    nombre      VARCHAR(100) NOT NULL, -- NOSONAR
    PRIMARY KEY (id),
    CONSTRAINT uq_permisos_nombre UNIQUE (nombre)
);

CREATE TABLE personas
(
    disabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    edad             SMALLINT,
    sexo             CHAR(1),                                    -- NOSONAR
    fecha_nacimiento TIMESTAMP(0),
    cedula           VARCHAR(15),                                -- NOSONAR
    telefono         VARCHAR(15),                                -- NOSONAR
    direccion        UUID        NOT NULL,
    id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    usuario          UUID,
    pasaporte        VARCHAR(20),                                -- NOSONAR
    estado           VARCHAR(50) NOT NULL DEFAULT 'NO_VALIDADO', -- NOSONAR
    apellido1        VARCHAR(100),                               -- NOSONAR
    apellido2        VARCHAR(100),                               -- NOSONAR
    nombre           VARCHAR(100),                               -- NOSONAR
    nombre2          VARCHAR(100),                               -- NOSONAR
    correo           VARCHAR(254),                               -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE provincias
(
    id     SMALLINT GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1),
    nombre VARCHAR(30) NOT NULL, -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    created_at  TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(0),
    descripcion VARCHAR(100),          -- NOSONAR
    nombre      VARCHAR(100) NOT NULL, -- NOSONAR
    PRIMARY KEY (id),
    CONSTRAINT uq_roles_rol UNIQUE (nombre)
);

CREATE TABLE roles_permisos
(
    permiso    SMALLINT     NOT NULL,
    rol        SMALLINT     NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0),
    PRIMARY KEY (permiso, rol)
);

CREATE TABLE sedes
(
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0),
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    region     VARCHAR(50), -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    last_used  TIMESTAMP(0),
    updated_at TIMESTAMP(0),
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    usuario    VARCHAR(50),           -- NOSONAR
    clave      VARCHAR(100) NOT NULL, -- NOSONAR
    PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_username UNIQUE (usuario)
);

CREATE TABLE usuarios_roles
(
    rol        INT          NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(0),
    usuario    UUID         NOT NULL,
    PRIMARY KEY (rol, usuario)
);

CREATE TABLE vacunas
(
    edad_minima_dias SMALLINT     NOT NULL,
    created_at       TIMESTAMP(0) NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(0),
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    nombre           VARCHAR(100) NOT NULL, -- NOSONAR
    dosis_maxima     VARCHAR(2),            -- NOSONAR
    PRIMARY KEY (id)
);

CREATE TABLE esquemas_vacunacion
(
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vacuna           UUID       NOT NULL,
    numero_dosis     VARCHAR(2) NOT NULL,
    intervalo_inicio INT,
    intervalo_fin    INT,
    CHECK (intervalo_inicio <= intervalo_fin)
);

-- indexes
CREATE INDEX ix_direcciones_direccion ON direcciones (direccion);

CREATE INDEX ix_distritos_nombre ON distritos (nombre);

CREATE INDEX ix_doctores_idoneidad ON doctores (idoneidad);

CREATE INDEX ix_fabricantes_licencia ON fabricantes (licencia);

CREATE UNIQUE INDEX ix_fabricantes_usuario ON fabricantes (usuario) WHERE usuario IS NOT NULL;

CREATE INDEX ix_permisos_nombre ON permisos (nombre);

CREATE INDEX ix_personas_nombres_apellidos ON personas (nombre, nombre2, apellido1, apellido2);

CREATE UNIQUE INDEX ix_entidades_correo ON entidades (correo) WHERE correo IS NOT NULL;

CREATE UNIQUE INDEX ix_entidades_telefono ON entidades (telefono) WHERE telefono IS NOT NULL;

CREATE UNIQUE INDEX ix_pacientes_id_temporal ON pacientes (identificacion_temporal) WHERE identificacion_temporal IS NOT NULL;

CREATE UNIQUE INDEX ix_personas_cedula ON personas (cedula) WHERE cedula IS NOT NULL;

CREATE UNIQUE INDEX ix_personas_pasaporte ON personas (pasaporte) WHERE pasaporte IS NOT NULL;

CREATE UNIQUE INDEX ix_personas_correo ON personas (correo) WHERE correo IS NOT NULL;

CREATE UNIQUE INDEX ix_personas_telefono ON personas (telefono) WHERE telefono IS NOT NULL;

CREATE UNIQUE INDEX ix_personas_usuario ON personas (usuario) WHERE usuario IS NOT NULL;

CREATE INDEX ix_provincias_nombre ON provincias (nombre);

CREATE INDEX ix_sedes_region ON sedes (region) WHERE region IS NOT NULL;

CREATE INDEX ix_usuarios_username ON usuarios (usuario);

CREATE INDEX ix_vacunas_nombre ON vacunas (nombre);

-- foreign key CONSTRAINTs
ALTER TABLE direcciones
    ADD CONSTRAINT fk_direcciones_distritos FOREIGN KEY (distrito) REFERENCES distritos (id);

ALTER TABLE distritos
    ADD CONSTRAINT fk_distritos_provincias FOREIGN KEY (provincia) REFERENCES provincias (id);

ALTER TABLE doctores
    ADD CONSTRAINT fk_doctores_sedes FOREIGN KEY (sede) REFERENCES sedes (id);

ALTER TABLE doctores
    ADD CONSTRAINT fk_doctores_personas FOREIGN KEY (id) REFERENCES personas (id);

ALTER TABLE dosis
    ADD CONSTRAINT fk_dosis_doctores FOREIGN KEY (doctor) REFERENCES doctores (id);

ALTER TABLE dosis
    ADD CONSTRAINT fk_dosis_pacientes FOREIGN KEY (paciente) REFERENCES pacientes (id);

ALTER TABLE dosis
    ADD CONSTRAINT fk_dosis_sedes FOREIGN KEY (sede) REFERENCES sedes (id);

ALTER TABLE dosis
    ADD CONSTRAINT fk_dosis_vacunas FOREIGN KEY (vacuna) REFERENCES vacunas (id);

ALTER TABLE entidades
    ADD CONSTRAINT fk_entidades_direcciones FOREIGN KEY (direccion) REFERENCES direcciones (id);

ALTER TABLE fabricantes
    ADD CONSTRAINT fk_fabricantes_usuarios FOREIGN KEY (usuario) REFERENCES usuarios (id);

ALTER TABLE fabricantes
    ADD CONSTRAINT fk_fabricantes_entidades FOREIGN KEY (id) REFERENCES entidades (id);

ALTER TABLE fabricantes_vacunas
    ADD CONSTRAINT fk_fabricantes_vacunas_vacunas FOREIGN KEY (vacuna) REFERENCES vacunas (id);

ALTER TABLE fabricantes_vacunas
    ADD CONSTRAINT fk_fabricantes_vacunas_fabricantes FOREIGN KEY (fabricante) REFERENCES fabricantes (id);

ALTER TABLE pacientes
    ADD CONSTRAINT fk_pacientes_personas FOREIGN KEY (id) REFERENCES personas (id);

ALTER TABLE personas
    ADD CONSTRAINT fk_personas_direcciones FOREIGN KEY (direccion) REFERENCES direcciones (id);

ALTER TABLE personas
    ADD CONSTRAINT fk_personas_usuarios FOREIGN KEY (usuario) REFERENCES usuarios (id);

ALTER TABLE roles_permisos
    ADD CONSTRAINT fk_roles_permisos_permisos FOREIGN KEY (permiso) REFERENCES permisos (id);

ALTER TABLE roles_permisos
    ADD CONSTRAINT fk_roles_permisos_roles FOREIGN KEY (rol) REFERENCES roles (id);

ALTER TABLE sedes
    ADD CONSTRAINT fk_sedes_entidades FOREIGN KEY (id) REFERENCES entidades (id);

ALTER TABLE usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_roles FOREIGN KEY (rol) REFERENCES roles (id);

ALTER TABLE usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_usuarios FOREIGN KEY (usuario) REFERENCES usuarios (id);

ALTER TABLE esquemas_vacunacion
    ADD CONSTRAINT fk_esquemas_vacunacion_vacuna FOREIGN KEY (vacuna) REFERENCES vacunas (id);
