name: Validate Gradle Wrapper

on: [ push, pull_request ]

jobs:
    validation:
        name: "Validate gradle wrapper"
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: gradle/actions/wrapper-validation@v4
